name: CpsCounter
main: sakura.kooi.CpsCounter.CpsCounter
version: 3
author: SakuraKooi
commands:
  cps:
    description: get other player cps
    usage: /cps
permissions:
  cpscounter.cps:
    default: op
  cpscounter.bypass:
    default: op